### ISSUE TITLE
Stay authenticated

### ISSUE THREAD

**Issue by Tiebe** [MrWouterNL/Zermelo4J#4]
If I enter an access code, I believe it's only valid for 16 hours. Is it possible to automatically re-authenticate so I don't have to enter a code every 16 hours?

Thank you in advance,

Tiebe

**Comment by wouterdedroog** [comment]
I had no issues with code validity, do you store the "Koppel App" code or the actual access token?

**Comment by wouterdedroog** [comment]
@Tiebe mocht dit nog een probleem zijn voel je vrij om de issue te heropenen
